


dev:
	php -S localhost:8000


publish:
	scp index.html globe@eeecon.uibk.ac.at:~/public_html
	rsync -va js globe@eeecon.uibk.ac.at:~/public_html/
	rsync -va tiles globe@eeecon.uibk.ac.at:~/public_html/


npm:
	npm install jquery
